README.md, aioguardian/__init__.py, aioguardian/client.py, aioguardian/device.py, aioguardian/errors.py, examples/test_client.py, examples/test_client_async.py, pyproject.toml, requirements_test.txt, tests/common.py, tests/fixtures/__init__.py, tests/fixtures/ping_failure_response.json, tests/fixtures/ping_success_response.json, tests/test_client.py, tests/test_device_api.py
This PR adds support for a base `Client` object and a method to run the `ping` command.
N/A
**Checklist:**
=> Add base client and support for ping command

.github/release-drafter.yml
This PR adds the `maintenance` label to Release Drafter.
N/A
**Checklist:**
=> Add "maintenance" as a Release Drafter label

README.md, aioguardian/device.py, examples/test_client.py, examples/test_client_async.py, tests/device/test_diagnostics.py, tests/device/test_ping.py, tests/fixtures/diagnostics_failure_response.json, tests/fixtures/diagnostics_success_response.json, tests/test_client.py
This PR provides support for running the diagnostics command.
N/A
**Checklist:**
=> Add support for diagnostics command

README.md, aioguardian/client.py, aioguardian/device.py, examples/test_client.py, examples/test_client_async.py, tests/device/test_diagnostics.py, tests/device/test_reboot.py, tests/fixtures/reboot_failure_response.json, tests/fixtures/reboot_success_response.json
This PR adds support for rebooting a device.
N/A
**Checklist:**
=> Add support for the reboot command

README.md, aioguardian/device.py, examples/test_client.py, examples/test_client_async.py, tests/device/test_factory_reset.py, tests/fixtures/factory_reset_failure_response.json, tests/fixtures/factory_reset_success_response.json
This PR adds support for factory resetting the device.
N/A
**Checklist:**
=> Add support for the factory_reset command

README.md, aioguardian/client.py, aioguardian/device.py, examples/test_client.py, examples/test_client_async.py, tests/device/test_firmware_upgrade.py, tests/fixtures/upgrade_firmware_failure_response.json, tests/fixtures/upgrade_firmware_success_response.json
This PR adds the ability to initiate firmware upgrades on the device.
Additionally, this PR adds Sphinx-friendly docstrings to everything.
N/A
**Checklist:**
=> Add support for the upgrade_firmware command

README.md, aioguardian/client.py, aioguardian/commands/valve.py, aioguardian/helpers/command.py, examples/test_client.py, tests/fixtures/valve_status_failure_response.json, tests/fixtures/valve_status_success_response.json, tests/test_valve_commands.py
This PR adds support for getting information from the valve itself.
N/A
**Checklist:**
=> Add support for the valve_status command

aioguardian/client.py, aioguardian/errors.py, tests/test_client.py, tests/test_device_commands.py, tests/test_sensor_commands.py, tests/test_valve_commands.py
This PR abstracts error handling during command execution so that we can do more complex handling later on without gunking up `client.execute_command`.
N/A
**Checklist:**
=> Abstract command error handling

README.md, aioguardian/commands/valve.py, aioguardian/errors.py, aioguardian/helpers/command.py, examples/test_client.py, tests/fixtures/valve_open_failure_response.json, tests/fixtures/valve_open_success_response.json, tests/test_device_commands.py, tests/test_sensor_commands.py, tests/test_valve_commands.py
This PR adds support for opening the valve.
N/A
**Checklist:**
=> Add support for valve_open command

README.md, aioguardian/commands/valve.py, aioguardian/helpers/command.py, examples/test_client.py, tests/fixtures/valve_close_failure_response.json, tests/fixtures/valve_close_success_response.json, tests/test_valve_commands.py
This PR adds support for closing the valve.
N/A
**Checklist:**
=> Add support for the valve_close command

README.md, aioguardian/commands/valve.py, aioguardian/helpers/command.py, examples/test_client.py, tests/fixtures/valve_halt_failure_response.json, tests/fixtures/valve_halt_success_response.json, tests/test_valve_commands.py
This PR adds support for halting the valve.
N/A
**Checklist:**
=> Add support for the halt command

README.md, aioguardian/commands/device.py, aioguardian/helpers/command.py, examples/test_client.py, tests/fixtures/wifi_status_failure_response.json, tests/fixtures/wifi_status_success_response.json, tests/test_device_commands.py
This PR adds support for getting WiFi connection details.
N/A
**Checklist:**
=> Add support for the wifi_status command

README.md, aioguardian/commands/device.py, aioguardian/helpers/command.py, examples/test_client.py, tests/fixtures/wifi_reset_failure_response.json, tests/fixtures/wifi_reset_success_response.json, tests/test_device_commands.py
This PR adds support for resetting the device's WiFi info and settings.
N/A
**Checklist:**
=> Add support for the wifi_reset command

aioguardian/client.py, aioguardian/commands/device.py, aioguardian/commands/sensor.py, aioguardian/commands/valve.py, aioguardian/errors.py
This PR cleans up missing typing and incorrect docstrings.
N/A
**Checklist:**
=> Various typing and docstring cleanup

README.md, aioguardian/commands/device.py, aioguardian/helpers/command.py, examples/test_client.py, pyproject.toml, requirements_test.txt, tests/fixtures/wifi_configure_failure_response.json, tests/fixtures/wifi_configure_success_response.json, tests/test_device_commands.py
This PR adds support for connecting the device to an SSID.
N/A
**Checklist:**
=> Add support for the wifi_configure command

aioguardian/commands/device.py, tests/test_device/test_upgrade_firmware.py, tests/test_device/test_wifi_configure.py
This PR strengthens the parameter schemas for the `upgrade_firmware` and `wifi_configure` commands.
N/A
**Checklist:**
=> Strengthen schemas for commands that take parameters

README.md, aioguardian/commands/device.py, aioguardian/commands/sensor.py, aioguardian/helpers/command.py, aioguardian/helpers/config_validation.py, examples/test_client.py, tests/fixtures/pair_sensor_failure_response.json, tests/fixtures/pair_sensor_success_response.json, tests/test_device/test_upgrade_firmware.py, tests/test_sensor/test_pair_dump.py, tests/test_sensor/test_pair_sensor.py
This PR adds the ability to pair an external sensor to the device.
N/A
**Checklist:**
=> Add support for the pair_sensor command

.github/release-drafter.yml, .gitignore, README.md, aioguardian/client.py, aioguardian/commands/device.py, aioguardian/commands/sensor.py, aioguardian/commands/valve.py, aioguardian/errors.py, aioguardian/helpers/config_validation.py, docs/Makefile, docs/api.rst, docs/commands.rst, docs/conf.py, docs/index.rst, docs/intro.rst, docs/make.bat, docs/usage.rst, pyproject.toml, script/docs
This PR adds Sphinx docs for Read the Docs.
N/A
**Checklist:**
=> Add Read the Docs documentation

.github/pull_request_template.md, README.md, aioguardian/commands/device.py, aioguardian/commands/sensor.py, aioguardian/commands/valve.py, aioguardian/errors.py, docs/api.rst, docs/usage.rst
This PR fixes various documentation odds and ends.
**Checklist:**
=> Fix various docstrings and Sphinx docs

README.md, aioguardian/client.py, aioguardian/commands/device.py, aioguardian/commands/sensor.py, aioguardian/commands/valve.py, docs/commands.rst, tests/common.py, tests/fixtures/ping_success_silent_response.json, tests/test_device/test_ping.py
This PR adds support for silencing the beeps the accompany any command other than one that affects the valve physical state. This is enabled on those coroutines by default.
N/A
**Checklist:**
=> Add support for silencing beeps in most commands

aioguardian/client.py, tests/conftest.py, tests/test_client.py
This PR adds retry logic to the commands.
Associated with #40 
**Checklist:**
=> Add retry logic

.github/release-drafter.yml
This PR adds the generation of a "Breaking Changes" section to Release Drafter.
N/A
**Checklist:**
=> Add "Breaking Changes" section to Release Drafter

aioguardian/commands/sensor.py, aioguardian/errors.py, aioguardian/helpers/command.py, docs/commands.rst, tests/commands/sensor/test_pair_dump.py, tests/commands/sensor/test_pair_sensor.py, tests/commands/sensor/test_paired_sensor_status.py, tests/commands/sensor/test_unpair_sensor.py, tests/commands/system/test_diagnostics.py, tests/commands/system/test_factory_reset.py, tests/commands/system/test_onboard_sensor_status.py, tests/commands/system/test_ping.py, tests/commands/system/test_reboot.py, tests/commands/system/test_upgrade_firmware.py, tests/commands/valve/test_close.py, tests/commands/valve/test_halt.py, tests/commands/valve/test_open.py, tests/commands/valve/test_reset.py, tests/commands/valve/test_status.py, tests/commands/wifi/test_configure.py, tests/commands/wifi/test_disable_ap.py, tests/commands/wifi/test_enable_ap.py, tests/commands/wifi/test_reset.py, tests/commands/wifi/test_status.py, tests/fixtures/pair_dump_success_response.json, tests/fixtures/paired_sensor_status_failure_3_response.json, tests/fixtures/paired_sensor_status_failure_5_response.json, tests/fixtures/paired_sensor_status_success_response.json
This PR adds support for getting the status of paired sensors.
N/A
**Checklist:**
=> Add support for getting the status of paired sensors

aioguardian/commands/wifi.py, aioguardian/helpers/command.py, docs/commands.rst, tests/commands/wifi/test_list.py, tests/commands/wifi/test_scan.py, tests/fixtures/wifi_list_failure_response.json, tests/fixtures/wifi_list_success_response.json, tests/fixtures/wifi_scan_failure_response.json, tests/fixtures/wifi_scan_success_response.json
This PR adds support for scanning/listing nearby WiFi SSIDs that the valve controller can see.
N/A
**Checklist:**
=> Add support for scanning and listing available SSIDs

.github/workflows/ci.yaml, .pre-commit-config.yaml, README.md, docs/usage.rst, pyproject.toml
This PR officially adds support for Python 3.9.
N/A
**Checklist:**
=> Add support for Python 3.9

aioguardian/client.py, aioguardian/commands/iot.py, aioguardian/commands/sensor.py, aioguardian/commands/system.py, aioguardian/commands/valve.py, aioguardian/commands/wifi.py, pyproject.toml
This PR enforces strict type-checking.
**Checklist:**
=> Enable strict type-checking

pyproject.toml
This PR loosens the dependency pinning for voluptuous. Adjusted to still allow old version.
**Checklist:**
=> Loosen dependency pin for voluptuous

docs/conf.py
This PR makes the copyright year in the docs dynamic.
N/A
**Checklist:**
=> Make docs copyright date dynamic

README.md, docs/usage.rst, pyproject.toml
This PR makes Python 3.8 the minimum supported version.
N/A
**Checklist:**
=> Make Python 3.8 the minimum version

.pre-commit-config.yaml, aioguardian/client.py, aioguardian/errors.py
This PR adds the [`pyupgrade`](https://github.com/asottile/pyupgrade) pre-commit hook to help us take advantage of new Python features depending on what versions we support.
N/A
**Checklist:**
=> Add pyupgrade pre-commit hook

aioguardian/commands/iot.py, aioguardian/commands/sensor.py, aioguardian/commands/system.py, aioguardian/commands/valve.py, aioguardian/commands/wifi.py
With some more intelligent typing, we can remove several redundant `cast` statements.
N/A
**Checklist:**
=> Remove unnecessary `cast` statements

aioguardian/client.py, aioguardian/commands/valve.py, aioguardian/commands/wifi.py, aioguardian/const.py
=> Use same logger throughout library

README.md, docs/index.md
1. Clean up docs verbiage
2. Use better linking style in the README
N/A
**Checklist:**
=> Clean up docs

.readthedocs.yml, poetry.lock, pyproject.toml
At some point, our RTD builds started failing. This PR fixes things.
**Checklist:**
=> Fix RTD builds

poetry.lock, pyproject.toml
Follows up #288.
N/A
**Checklist:**
=> Remove `setuptools` from dependencies

poetry.lock, pyproject.toml
=> Remove Vulture

pyproject.toml
=> chore: remove Vulture from `pyproject.toml`

pyproject.toml
- N/A, [SSIA][ssia]
- N/A
- N/A
- N/A
[ssia]: https://en.wiktionary.org/wiki/SSIA
=> chore: ensure `pylint` uses lowest supported Python version

script/release
- N/A, [SSIA][ssia]
- N/A
- N/A
- N/A
[ssia]: https://en.wiktionary.org/wiki/SSIA
=> ci: ensure that release process updates `uv.lock`

script/setup
- N/A, [SSIA][ssia]
- N/A
- N/A
- N/A
[ssia]: https://en.wiktionary.org/wiki/SSIA
=> build: streamline how `uv` is installed in `script/setup`
