bachya/aioguardian

tests/conftest.py
tests/test_device_api.py

Since I anticipate all future tests will need to mock a datagram client (to simulate responses from the device), this PR turns that functionality into an easy-to-use fixture.
N/A
**Checklist:**

Turn mock_datagram_client into a fixture

---

aioguardian/client.py
aioguardian/device.py
examples/test_client_async.py

Previously, the `Client` object was injecting two methods into its composed objects: one to run a command against the Guardian device and one to wrap that command in a Future for `asyncio` use. This was bad: composed objects should have no knowledge of the `Client`'s internal workings like that. This PR streamlines things.
Additionally, this fixes a small bug in the async client example.
N/A
**Checklist:**

Streamline commmand execution method

---

README.md
aioguardian/client.py
examples/test_client.py
tests/test_client.py
tests/test_device_commands.py

This PR creates an async context manager for `Client`, which allows users to focus on sending commands and let connection/disconnection be handled for them.
N/A
**Checklist:**

Create async context manager for `Client` objects

---

aioguardian/client.py
aioguardian/device.py
aioguardian/helpers/__init__.py
aioguardian/helpers/command.py
tests/test_client.py
tests/test_device_commands.py

This PR adds the concept of a `Command` class (via a helper) that associates a friendly command name with the integer that the Guardian API specifies. This does two things:
1. Abstracts the connection between command and integer such that sub-classes (like `device`) don't need to know about the integers
2. Makes it possible to provide better logging when a command fails
**Checklist:**

Create Command helper

---

aioguardian/client.py

We failed to properly implement timeout control when connecting via the `Client`. This PR fixes that.
N/A
**Checklist:**

Fix incorrect async timeout in client connect

---

aioguardian/client.py

This PR removes the `event_loop` parameter when creating a `Client` because it was a vestige of [our previous sync/async experiment](https://github.com/bachya/aioguardian/pull/9) and is no longer needed.
N/A
**Checklist:**

Remove event loop attribute in Client

---

aioguardian/client.py

This PR adds a parameter to the `Client` class that allows the request timeout (which defaults to 10 seconds) to be configurable.
N/A
**Checklist:**

Allow request timeout to be configurable

---

aioguardian/__init__.py
aioguardian/commands/valve.py
tests/test_valve_commands.py

Previously, `client.valve.valve_status` would return an integer for the valve's state. According to the API docs, there are 13 different states; this PR creates a more human-friendly representation that doesn't rely on people knowing what the integers mean.
N/A
**Checklist:**

Create a more friendly representation of the valve status

---

aioguardian/__init__.py
aioguardian/commands/valve.py
tests/test_valve_commands.py

#17 used an `Enum` to represent the valve state, but in practice, that seems like too much overhead (especially since it would force users to import that `Enum` to compare values). This PR transitions the state representation to a set of string constants.
N/A
**Checklist:**

Change valve state representation to constants (instead of Enum)

---

aioguardian/commands/device.py
tests/test_device_commands.py

The Guardian API docs make this statement about the reboot command:
>The restart will occur 3 seconds after command is received.
In order to guard against possible errors from subsequent commands while the reboot is occurring, this PR adds a 3-second sleep to account for this.
N/A
**Checklist:**

Sleep for 3 seconds after issuing a reboot command

---

README.md
aioguardian/commands/device.py
aioguardian/helpers/command.py
examples/test_client.py
tests/fixtures/wifi_enable_ap_failure_response.json
tests/fixtures/wifi_enable_ap_success_response.json
tests/test_device/test_wifi_enable_ap.py

This PR adds support for enabling the device's onboard WiFi access point.
N/A
**Checklist:**

Add support for the wife_enable_ap command

---

README.md
aioguardian/commands/sensor.py
aioguardian/helpers/command.py
examples/test_client.py
tests/fixtures/pair_dump_failure_response.json
tests/fixtures/pair_dump_success_response.json
tests/test_client.py
tests/test_sensor/test_pair_dump.py

This PR adds support for the dumping info on all sensors paired to the device.
N/A
**Checklist:**

Add support for the pair_dump command

---

aioguardian/commands/device.py
aioguardian/helpers/command.py
examples/test_client.py
tests/fixtures/publish_state_failure_response.json
tests/fixtures/publish_state_success_response.json
tests/test_device/test_publish_state.py

This PR adds support for publishing the device's current state to the Guardian cloud.
N/A
**Checklist:**

Add support for the publish_state command

---

aioguardian/client.py
aioguardian/commands/valve.py
tests/test_client.py

At very sporadic times, the device returns the response for a different command than what was requested; this appears to be a bug in the device. `aioguardian` can't fix the issue, per se, so this PR raises a `CommandError` when this situation arises.
Guards against https://github.com/bachya/aioguardian/issues/40, but doesn't fix it; waiting to see if Elexa fixes the bug.
**Checklist:**

Raise when response doesn't match command

---

aioguardian/client.py

I wasn't using `async_timeout` correctly, which led to unhandled exceptions in actual timeouts. This PR fixes that.
Discovered via #40.
**Checklist:**

Fix bug with incorrect async_timeout usage

---

aioguardian/client.py
tests/test_client.py

According to the Elexa engineer I've been working with, #40 can happen because the device is only using a single UDP socket – there will be times where a device timeout happens and gums up the works for other commands. This PR is part of a solution for #40: it adds a locking mutex to command execution to ensure there's no concurrency.
Related to #40 
**Checklist:**

Add a locking mutex to command execution

---

aioguardian/client.py
aioguardian/errors.py

This PR moves `_raise_on_command_error` out of `aioguardian.client` and into `aioguardian.errors`, which makes more sense.
N/A
**Checklist:**

Move command error helper to correct module

---

aioguardian/commands/iot.py
aioguardian/commands/sensor.py
aioguardian/commands/system.py
aioguardian/helpers/command.py
tests/commands/iot/test_publish_state.py
tests/commands/sensor/test_pair_dump.py
tests/commands/sensor/test_pair_sensor.py
tests/commands/sensor/test_unpair_sensor.py
tests/commands/system/test_diagnostics.py
tests/commands/system/test_factory_reset.py
tests/commands/system/test_onboard_sensor_status.py
tests/commands/system/test_ping.py
tests/commands/system/test_reboot.py
tests/commands/system/test_upgrade_firmware.py
tests/helpers/test_command.py
tests/test_client.py

Following up on #51, this PR adjusts internal command names to match the public-facing API.
N/A
**Checklist:**

Adjust internal command names to match groupings and API

---

aioguardian/commands/system.py
tests/commands/system/test_upgrade_firmware.py

I learned today that you can run the `system.upgrade_firmware` command without any URL, port, or firmware file. This PR relaxes the previous requirement of defaults.
N/A
**Checklist:**

Allow None values for system.upgrade_firmware parameters

---

.pre-commit-config.yaml
tests/async_mock.py
tests/commands/system/test_reboot.py
tests/conftest.py
tests/test_client.py

This PR fixes the fact that `asynctest` no longer works in Python 3.8. The PR still ensures that it can be used for Python 3.6 and 3.7.
Fixes https://github.com/bachya/aioguardian/issues/59
**Checklist:**

Handle asynctest not working in Python 3.8

---

pyproject.toml
requirements_test.txt

For reference:
- https://pypi.org/project/voluptuous/0.12.0/#files
- https://github.com/bachya/simplisafe-python/pull/174
- https://github.com/home-assistant/core/pull/40401#issuecomment-697283168
Updates the requirements on [voluptuous](https://github.com/alecthomas/voluptuous) to permit the latest version.
- [Release notes](https://github.com/alecthomas/voluptuous/releases)
- [Changelog](https://github.com/alecthomas/voluptuous/blob/master/CHANGELOG.md)
- [Commits](https://github.com/alecthomas/voluptuous/commits/v0.12.0)
- Resolves dependency conflicts with other modules that depend on latest voluptuous.
- Additionally: https://github.com/home-assistant/core/pull/40401#issue-490153791
**Checklist:**

Update voluptuous requirement from ^0.11.7 to >=0.11.7,<0.13.0

---

pyproject.toml
requirements_test.txt

Allow later `asyncio_dgram` releases. According to the [ChangeLog](https://github.com/jsbronder/asyncio-dgram/blob/master/ChangeLog) does the releases not contain breaking changes.
Distributions are starting to ship `asyncio_dgram` > 2. This is an issue for NixOS as others as `aioguardian` fails to build.
**Checklist:**

Allow later asyncio_dgram releases

---

pyproject.toml

Pull-in only `poetry-core`.
This allow distributions to only depend on the build backend and not the full poetry package.
**Checklist:**

Use poetry-core as dependency

---

pyproject.toml

Relaxes the async-timeout version constrains.
Home Assistant uses 4.0.0
```
ERROR: Cannot install -r requirements_test_all.txt (line 118), -r requirements_test_all.txt (line 24) and -r requirements_test_all.txt (line 54) because these package versions have conflicting dependencies.
The conflict is caused by:
pyrmvtransport 0.3.2 depends on async-timeout
adax 0.1.1 depends on async-timeout>=1.4.0
aioguardian 1.0.8 depends on async_timeout<4.0.0 and >=3.0.1
The user requested (constraint) async-timeout==4.0.0
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
**Checklist:**

Relax async-timeout dependency version constrain

---

.pre-commit-config.yaml
pyproject.toml
requirements_test.txt

This PR loosens the dependency pinning for `voluptuous`. It tangentially updates the version of `black` used in `pre-commit` to resolve conflicts.
Fixes https://github.com/bachya/aioguardian/issues/81
**Checklist:**

Loosen dependency pin for voluptuous

---

pyproject.toml

Remove docutils dependency.
If needed, then it should be either in dev-dependencies, or only in a requirements file for CI
Related to https://github.com/home-assistant/core/pull/68897
**Checklist:**

Remove docutils dependency

---

.pre-commit-config.yaml
docs/conf.py

This PR follows up on #96 to ensure that the `docs/` folder is also covered by pre-commit hooks.
N/A
**Checklist:**

Ensure docs are covered by pre-commit hooks

---

aioguardian/client.py

In some cases (like when pairing a sensor), the Guardian socket connection will force close after it completes – not sure why. In the current code, that throws an exception because we try to close a closed connection.
N/A
**Checklist:**

Guard against forced disconnections

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
README.md
docs/usage.md
pyproject.toml
tests/commands/system/test_ping.py

Happy Python 3.11 release day! This PR updates CI to tests against the GA release. Per our standards of supporting the three most recent versions, this PR also removes official support for anything before 3.9.
N/A
**Checklist:**

Update CI to use GA release of Python 3.11

---

aioguardian/commands/wifi.py
tests/commands/wifi/test_list.py

SSIA. This was only useful when first called; after, we might incorrectly prompt the user to believe that results are fresh when they aren't.
**Checklist:**

Remove incorrect warning about cached WiFi SSIDs
